import React from 'react';
import { createRoot } from 'react-dom/client';
import { Clock3, BarChart3, FileText, Truck, CheckCircle2, Phone, Mail, WalletCards, ShieldCheck, ArrowRight } from 'lucide-react';
import { motion } from 'framer-motion';
import './styles.css';

const services = [
  { icon: Clock3, title: 'Daily Bookkeeping Updates', text: 'We keep your books updated regularly so you can see where your business stands without waiting for month-end.' },
  { icon: WalletCards, title: 'AR & AP Tracking', text: 'Know who owes you money, what bills are due, and how your cash flow is moving.' },
  { icon: BarChart3, title: 'Live Financial Reports', text: 'View Profit & Loss, Balance Sheet, cash position, receivables, and payables anytime.' },
  { icon: FileText, title: 'GST/HST & Year-End Support', text: 'Stay organized for tax filings with clean books, reconciled accounts, and proper documentation.' }
];

const packages = [
  { name: 'Starter', price: '$299–$499/mo', bestFor: 'Owner-operators and very small businesses', items: ['Weekly bookkeeping', 'Bank reconciliation', 'Monthly P&L', 'GST/HST tracking'] },
  { name: 'Growth', price: '$599–$899/mo', bestFor: 'Small businesses that need current books', items: ['Daily/near daily updates', 'AR & AP tracking', 'Monthly reports', 'GST/HST filing support'], featured: true },
  { name: 'Pro', price: '$1,200+/mo', bestFor: 'Fleets and growing businesses', items: ['Daily bookkeeping', 'Full AR/AP management', 'Cash flow review', 'Monthly CPA review call'] }
];

function App() {
  return <div>
    <header className="header"><div className="wrap nav"><a className="brand" href="#top"><img src="/logo.png" alt="RealTime Books logo"/><div><strong>RealTime <span>Books</span></strong><small>Your Numbers. Updated Daily.</small></div></a><nav><a href="#services">Services</a><a href="#industries">Industries</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></nav><a className="btn primary" href="#contact">Book a Free Consultation</a></div></header>
    <main id="top">
      <section className="hero"><div className="wrap heroGrid"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><p className="pill">Built for small businesses that need current numbers</p><h1>Know Your Numbers—Every Day</h1><p className="lead">RealTime Books keeps your accounting updated daily, so you can make confident decisions without waiting for month-end reports.</p><div className="actions"><a className="btn gold" href="#contact">Book a Free Consultation <ArrowRight size={18}/></a><a className="btn outline" href="#services">View Services</a></div></motion.div><motion.div className="snapshot" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.1}}><div className="snapshotTop"><div><small>Today’s Snapshot</small><h3>Live Business View</h3></div><Clock3/></div>{['Cash Position','Accounts Receivable','Accounts Payable','Profit & Loss'].map(x=><div className="snapRow" key={x}><span>{x}</span><b>Updated</b></div>)}<p className="note">Most firms show reports after the month is over. We help you see your position while there is still time to act.</p></motion.div></div></section>
      <section className="wrap intro"><div className="introText"><h2>Most businesses do not fail because they lack work.</h2><p>They struggle because they do not see their numbers in time. RealTime Books helps small business owners stay in control with daily-updated bookkeeping, clear reporting, and practical financial visibility.</p></div><div className="trust"><ShieldCheck/><h3>CPA-backed service</h3><p>Professional accounting support designed for real business decisions—not only year-end filing.</p></div></section>
      <section id="services" className="section gray"><div className="wrap"><p className="eyebrow">Services</p><h2>Accounting that moves with your business</h2><div className="cards">{services.map(s=>{const Icon=s.icon; return <div className="card" key={s.title}><Icon className="cardIcon"/><h3>{s.title}</h3><p>{s.text}</p></div>})}</div></div></section>
      <section id="industries" className="section"><div className="wrap split"><div><p className="eyebrow">Industries</p><h2>Built first for trucking and small business owners</h2><p>We understand the pressure of fuel costs, repairs, receivables, payroll, GST/HST, and cash flow. Our service helps owners see what is happening before problems become expensive.</p>{['Trucking & logistics companies','Owner-operators','Small incorporated businesses','Growing service businesses'].map(i=><div className="check" key={i}><CheckCircle2/> {i}</div>)}</div><div className="truckBox"><Truck/><h3>For trucking companies</h3><p>See unpaid broker invoices, fuel and repair costs, loan payments, payroll expenses, and real profit in one organized system.</p></div></div></section>
      <section className="section blue"><div className="wrap"><p className="eyebrow goldText">How it works</p><h2>Simple setup. Daily visibility.</h2><div className="steps">{['We connect your bank, credit cards, and accounting system.','We collect invoices, receipts, and documents through simple workflows.','We update and review your books on a daily basis.','You get clear financial visibility whenever you need it.'].map((s,i)=><div className="step" key={s}><b>{i+1}</b><p>{s}</p></div>)}</div></div></section>
      <section id="pricing" className="section"><div className="wrap"><p className="eyebrow">Packages</p><h2>Monthly plans for different business sizes</h2><p className="muted">Final pricing depends on transaction volume, cleanup required, payroll, tax filing needs, and reporting level.</p><div className="pricing">{packages.map(p=><div className={'priceCard '+(p.featured?'featured':'')} key={p.name}>{p.featured&&<small>Most Popular</small>}<h3>{p.name}</h3><h4>{p.price}</h4><p>{p.bestFor}</p>{p.items.map(i=><div className="check" key={i}><CheckCircle2/> {i}</div>)}</div>)}</div></div></section>
      <section id="contact" className="section gray"><div className="wrap split"><div><p className="eyebrow">Contact</p><h2>Ready to see your numbers every day?</h2><p>Book a free consultation and we’ll review your current bookkeeping process, reporting gaps, and best setup for daily visibility.</p><div className="contactLine"><Mail/> accounts@realtimebooks.ca</div><div className="contactLine"><Phone/> 204-952-3102</div></div><form className="contactForm" action="https://formspree.io/f/YOUR_FORM_ID" method="POST"><input name="name" placeholder="Your Name" required/><input name="email" type="email" placeholder="Business Email" required/><input name="phone" placeholder="Phone Number"/><textarea name="message" placeholder="Tell us about your business" required></textarea><button className="btn primary" type="submit">Send Message</button><p className="formNote">Form needs your Formspree ID before launch.</p></form></div></section>
    </main><footer><div className="wrap foot"><div><strong>RealTime <span>Books</span></strong><p>Your Numbers. Updated Daily.</p></div><p>© 2026 RealTime Books. All rights reserved.</p></div></footer>
  </div>
}

createRoot(document.getElementById('root')).render(<App/>);
